"""add extra bed in booking

Revision ID: 3f57fc6e3947
Revises: b6e2a9b6729a
Create Date: 2025-12-16 17:06:57.477037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f57fc6e3947'
down_revision: Union[str, Sequence[str], None] = 'b6e2a9b6729a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('extra_bed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'extra_bed')
    # ### end Alembic commands ###
