"""update room TB2

Revision ID: 8c668e136a2e
Revises: 5dfb749268d2
Create Date: 2025-12-17 19:01:41.203035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c668e136a2e'
down_revision: Union[str, Sequence[str], None] = '5dfb749268d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_rooms_room_no'), 'rooms', ['room_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_rooms_room_no'), 'rooms', type_='unique')
    # ### end Alembic commands ###
