"""update custome TB

Revision ID: 9b658b10ae49
Revises: 3f57fc6e3947
Create Date: 2025-12-17 18:20:54.953773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b658b10ae49'
down_revision: Union[str, Sequence[str], None] = '3f57fc6e3947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_customers_email'), 'customers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_customers_email'), 'customers', type_='unique')
    # ### end Alembic commands ###
