"""initial schema

Revision ID: b6e2a9b6729a
Revises: 
Create Date: 2025-12-16 16:23:03.532569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e2a9b6729a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('telephone', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_table('room_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_type', sa.Enum('SINGLE', 'DOUBLE', name='roomtypeenum'), nullable=False),
    sa.Column('extra_bed', sa.Integer(), nullable=False),
    sa.Column('guest_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_type'))
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_no', sa.String(length=10), nullable=False),
    sa.Column('floor', sa.String(length=255), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_type.id'], name=op.f('fk_rooms_room_type_id_room_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms'))
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('total_guest', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'EXPIRED', name='statusenum'), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_booking_customer_id_customers')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_booking_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking'))
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('duedate', sa.Date(), nullable=False),
    sa.Column('is_paid', sa.Enum('PAID', 'UNPAID', name='paidenum'), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('paid_by', sa.String(length=255), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name=op.f('fk_invoices_booking_id_booking')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    op.drop_table('booking')
    op.drop_table('rooms')
    op.drop_table('room_type')
    op.drop_table('customers')
    # ### end Alembic commands ###
